service: sms-notification

provider:
  name: aws
  runtime: nodejs12.x

  stage: dev
  region: us-east-1

functions:
  send_sms:
    handler: handler.send
    role: ${ssm:${self:custom.stage}-sms-iam-role}
    events:
      - sqs: ${ssm:${self:custom.stage}-sms-sqs}
    environment:
      MESSAGE_BIRD_API_KEY: ${ssm:${self:custom.stage}-message_bird_api_key}
      SMS_PHONE_FROM: ${ssm:${self:custom.stage}-sms_phone_from}
      SMS_PHONE_TO: ${ssm:${self:custom.stage}-sms_phone_to}
custom:
  stage: ${opt:stage, self:provider.stage}
