service: email-notification

provider:
  name: aws
  runtime: nodejs12.x

  stage: dev
  region: us-east-1

functions:
  send_email:
    handler: handler.send
    role: ${ssm:${self:custom.stage}-email-iam-role}
    events:
      - sqs: ${ssm:${self:custom.stage}-email-sqs}
    environment:
      EMAIL_FROM: ${ssm:${self:custom.stage}-email_from}
      EMAIL_FROM_PASSWORD: ${ssm:${self:custom.stage}-email_from_password}
      EMAIL_TO: ${ssm:${self:custom.stage}-email_to}
      SMTP_SERVER: ${ssm:${self:custom.stage}-smtp_server}
custom:
  stage: ${opt:stage, self:provider.stage}
